In [3]:
# HW QUESTIONS (NUMPY)

import numpy as np

In [4]:
#Define two custom numpy arrays A and B
A = np.array([[1, 5, 9],
              [4, 7, 2]])
B = np.array([[3, 5, 8],
              [1, 7, 6]])

print("Array A:\n", A)
print("\nArray B:\n", B)

Array A:
 [[1 5 9]
 [4 7 2]]

Array B:
 [[3 5 8]
 [1 7 6]]


In [5]:
#Stack A and B vertically and horizontally
vertical_stack = np.vstack((A, B))
horizontal_stack = np.hstack((A, B))

print("\nVertically stacked (A over B):\n", vertical_stack)
print("\nHorizontally stacked (A beside B):\n", horizontal_stack)


Vertically stacked (A over B):
 [[1 5 9]
 [4 7 2]
 [3 5 8]
 [1 7 6]]

Horizontally stacked (A beside B):
 [[1 5 9 3 5 8]
 [4 7 2 1 7 6]]


In [6]:
#Find common elements between A and B (intersection)
common_elements = np.intersect1d(A, B)
print("\nCommon elements between A and B:\n", common_elements)


Common elements between A and B:
 [1 5 7]


In [7]:
#Extract all numbers from A which are between 5 and 10
filtered_A = A[(A >= 5) & (A <= 10)]
print("\nNumbers in A between 5 and 10:\n", filtered_A)


Numbers in A between 5 and 10:
 [5 9 7]


In [8]:
#Filter rows of iris_2d with petallength > 1.5 and sepallength < 5.0
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

filtered_iris = iris_2d[(iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)]
print("\nFiltered iris rows (petal length > 1.5 and sepal length < 5.0):\n", filtered_iris)


Filtered iris rows (petal length > 1.5 and sepal length < 5.0):
 [[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


In [9]:
# HW QUESTIONS (PANDAS)
import pandas as pd


In [10]:
#Filter 'Manufacturer', 'Model', and 'Type' for every 20th row starting from row 0
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
filtered_df = df.loc[::20, ['Manufacturer', 'Model', 'Type']]
print("\nEvery 20th row (Manufacturer, Model, Type):\n", filtered_df)


Every 20th row (Manufacturer, Model, Type):
    Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


In [11]:
#Replace missing values in Min.Price and Max.Price columns with their respective mean
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
df['Min.Price'].fillna(df['Min.Price'].mean(), inplace=True)
df['Max.Price'].fillna(df['Max.Price'].mean(), inplace=True)
print("\nMissing values in Min.Price and Max.Price replaced with their mean:")
print(df[['Min.Price', 'Max.Price']].head())


Missing values in Min.Price and Max.Price replaced with their mean:
   Min.Price  Max.Price
0  12.900000  18.800000
1  29.200000  38.700000
2  25.900000  32.300000
3  17.118605  44.600000
4  17.118605  21.459091


/tmp/ipython-input-2879391957.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Min.Price'].fillna(df['Min.Price'].mean(), inplace=True)
/tmp/ipython-input-2879391957.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=Tr

In [12]:
#Get rows of a dataframe with row sum > 100
df_random = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4),
                         columns=['A', 'B', 'C', 'D'])
filtered_rows = df_random[df_random.sum(axis=1) > 100]

print("\nRandom DataFrame:\n", df_random)
print("\nRows with row sum > 100:\n", filtered_rows)


Random DataFrame:
      A   B   C   D
0   30  20  13  31
1   30  39  28  12
2   19  15  37  30
3   35  14  28  32
4   18  21  38  31
5   20  33  29  14
6   26  15  33  19
7   22  19  35  23
8   37  24  20  37
9   20  36  12  19
10  28  18  28  16
11  18  33  15  24
12  32  23  32  12
13  25  11  18  29
14  18  31  16  32

Rows with row sum > 100:
     A   B   C   D
1  30  39  28  12
2  19  15  37  30
3  35  14  28  32
4  18  21  38  31
8  37  24  20  37
